spring:
  profiles:
    include: secret
  servlet:
    multipart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/dailydirector
    username: haneol
    password: haneol123
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
#    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html


server:
  port: 8080
  tomcat:
    connection-timeout: 30000
#    max-threads: 100
#    min-spare-threads: 50
#    accept-count: 50
    uri-encoding: UTF-8
  forward-headers-strategy: framework

jwt:
  secret:
    key: 47362e25dda1b5e90d840d741d8b59f573852175df08a8e7d1b8ce9a234ccfd8c6d1d72331eee73b6e429a6c987ef9529daa16696bdc9d6f2c7d429b73ff812a
# TODO static 변수 등록 어디에 하나?

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace